# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'enter_screen1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QMutex

import photos2

from log_in_screen1 import Ui_LogInWindow, show_window
class Ui_startWindow(object):
    def __init__(self, Client):
        self.client = Client
        self.log_in = Ui_LogInWindow(self.client)

    def setupUi(self, startWindow):
        startWindow.setObjectName("startWindow")
        startWindow.resize(800, 610)
        startWindow.setStyleSheet("background-color:rgb(18, 18, 18);\n"
                                  "")
        self.centralwidget = QtWidgets.QWidget(startWindow)
        self.centralwidget.setObjectName("centralwidget")
        self._mutex = QMutex()
        self.log_in_button = QtWidgets.QPushButton(self.centralwidget)
        self.log_in_button.setGeometry(QtCore.QRect(320, 450, 161, 41))
        self.log_in_button.setStyleSheet(";background-color: rgb(162, 47, 255);\n"
                                         "font: 75 8pt \"Magneto\"; font-size: 35px;height: 20px;width: 45px;")
        self.log_in_button.setObjectName("log_in_button")
        self.sign_up_button = QtWidgets.QPushButton(self.centralwidget)
        self.sign_up_button.setGeometry(QtCore.QRect(320, 390, 161, 41))
        self.sign_up_button.setStyleSheet(";background-color: rgb(162, 47, 255);\n"
                                          "font: 75 8pt \"Magneto\"; font-size: 35px;height: 20px;width: 45px;")
        self.sign_up_button.setObjectName("sign_up_button")
        self.logo_image = QtWidgets.QLabel(self.centralwidget)
        self.logo_image.setGeometry(QtCore.QRect(40, -10, 721, 381))
        self.logo_image.setMaximumSize(QtCore.QSize(721, 16777215))
        self.logo_image.setPixmap(QtGui.QPixmap(":/photos2/logo.png"))
        self.logo_image.setObjectName("logo_image")
        startWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(startWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        startWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(startWindow)
        self.statusbar.setObjectName("statusbar")
        startWindow.setStatusBar(self.statusbar)

        self.retranslateUi(startWindow)
        QtCore.QMetaObject.connectSlotsByName(startWindow)
        self.check_for_button(startWindow)

    def retranslateUi(self, startWindow):
        _translate = QtCore.QCoreApplication.translate
        startWindow.setWindowTitle(_translate("startWindow", "MainWindow"))
        self.log_in_button.setText(_translate("startWindow", "Log-In"))
        self.sign_up_button.setText(_translate("startWindow", "Sign-Up"))
        self.logo_image.setText(
            _translate("startWindow", "<html><head/><body><p><img src=\":/photos2/logo2.png\"/></p></body></html>"))

    def check_for_button(self, MainWindow):
        self.sign_up_button.clicked.connect(lambda: self.signuppressed(MainWindow))
        self.log_in_button.clicked.connect(lambda: self.loginpressed(MainWindow))

    def signuppressed(self, MainWindow):
        print("sign-up pressed")
        self._mutex.lock()
        self.client.screen_state = 0
        self._mutex.unlock()
        MainWindow.close()

    def loginpressed(self, MainWindow):
        print("log-in pressed")
        self._mutex.lock()
        self.client.screen_state = 1
        self._mutex.unlock()
        MainWindow.close()


def show_win(window):
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    window.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
