# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'log_in_screen1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import time

from PyQt5 import QtCore, QtGui, QtWidgets
import sys

from PyQt5.QtCore import QMutex


class Ui_LogInWindow(object):
    def __init__(self, Client):
        self.client = Client

    def setupUi(self, LogInWindow):
        LogInWindow.setObjectName("LogInWindow")
        LogInWindow.resize(800, 750)
        LogInWindow.setMinimumSize(QtCore.QSize(760, 750))
        LogInWindow.setStyleSheet("background-color:rgb(18, 18, 18);\n"
                                  "")
        self.centralwidget = QtWidgets.QWidget(LogInWindow)
        self.centralwidget.setObjectName("centralwidget")
        self._mutex = QMutex()
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, -20, 721, 381))
        self.label.setMinimumSize(QtCore.QSize(721, 381))
        self.label.setPixmap(QtGui.QPixmap(":/photos/gamelogo.png"))
        self.label.setObjectName("label")
        self.log_in_data = QtWidgets.QPushButton(self.centralwidget)
        self.log_in_data.setGeometry(QtCore.QRect(590, 450, 121, 71))
        self.log_in_data.setStyleSheet("background-color: rgb(0, 255, 255);\n"
                                       "font: 75 8pt \"Magneto\"; font-size: 35px;height: 20px;width: 45px;\n"
                                       "")
        self.log_in_data.setObjectName("log_in_data")
        self.robot_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.robot_checkbox.setGeometry(QtCore.QRect(590, 420, 121, 20))
        self.robot_checkbox.setStyleSheet(";background-color: rgb(253, 253, 253);")
        self.robot_checkbox.setObjectName("robot_checkbox")
        self.robot_label = QtWidgets.QLabel(self.centralwidget)
        self.robot_label.setGeometry(QtCore.QRect(590, 390, 121, 20))
        self.robot_label.setStyleSheet(";background-color: rgb(253, 253, 253);")
        self.robot_label.setObjectName("robot_label")
        self.robot_label.hide()
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(290, 630, 191, 31))
        self.label_2.setStyleSheet(";background-color: rgb(253, 253, 253);")
        self.label_2.setObjectName("label_2")
        self.label_2.hide()
        self.player_in = QtWidgets.QLabel(self.centralwidget)
        self.player_in.setGeometry(QtCore.QRect(290, 670, 191, 31))
        self.player_in.setStyleSheet(";background-color: rgb(253, 253, 253);")
        self.player_in.setObjectName("player_in")
        self.player_in.hide()
        self.username_label = QtWidgets.QLabel(self.centralwidget)
        self.username_label.setGeometry(QtCore.QRect(200, 410, 351, 20))
        self.username_label.setStyleSheet(";background-color:rgb(255, 0, 0);\n"
                                          "font: 75 8pt \"Magneto\"; font-size: 20px;height: 10px;width: 30px;")
        self.username_label.setObjectName("username_label")

        self.username_text = QtWidgets.QLineEdit(self.centralwidget)
        self.username_text.setGeometry(QtCore.QRect(200, 430, 351, 61))
        self.username_text.setStyleSheet(";background-color: rgb(162, 47, 255);\n"
                                         "font: 75 8pt \"Magneto\"; font-size: 35px;height: 20px;width: 45px;")
        self.username_text.setObjectName("username_text")
        self.password_text = QtWidgets.QLineEdit(self.centralwidget)
        self.password_text.setGeometry(QtCore.QRect(200, 530, 351, 61))
        self.password_text.setStyleSheet(";background-color: rgb(162, 47, 255);\n"
                                         "font: 75 8pt \"Magneto\"; font-size: 35px;height: 20px;width: 45px;")
        self.password_text.setObjectName("password_text")
        self.password_label = QtWidgets.QLabel(self.centralwidget)
        self.password_label.setGeometry(QtCore.QRect(200, 510, 351, 21))
        self.password_label.setStyleSheet(";background-color:rgb(255, 0, 0);\n"
                                          "font: 75 8pt \"Magneto\"; font-size: 20px;height: 10px;width: 30px;")
        self.password_label.setObjectName("password_label")
        LogInWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LogInWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        LogInWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LogInWindow)
        self.statusbar.setObjectName("statusbar")
        LogInWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LogInWindow)
        QtCore.QMetaObject.connectSlotsByName(LogInWindow)
        self.check_for_button_log(LogInWindow)

    def retranslateUi(self, LogInWindow):
        _translate = QtCore.QCoreApplication.translate
        LogInWindow.setWindowTitle(_translate("LogInWindow", "MainWindow"))
        self.label.setText(
            _translate("LogInWindow", "<html><head/><body><p><img src=\":/photos2/logo.png\"/></p></body></html>"))
        self.log_in_data.setText(_translate("LogInWindow", "log-in"))
        self.robot_checkbox.setText(_translate("LogInWindow", "I am not a robot"))
        self.label_2.setText(_translate("LogInWindow", " username or password are incorrect!"))
        self.robot_label.setText(_translate("LogInWindow", " you might be a robot"))
        self.player_in.setText(_translate("LogInWindow", " player already logged"))
        self.username_label.setText(_translate("signUpWindow", " username:"))
        self.password_label.setText(_translate("signUpWindow", " password:"))

    def check_for_button_log(self, MainWindow):
        self.log_in_data.clicked.connect(lambda: self.log_in_pressed(MainWindow))

    def log_in_pressed(self, MainWindow):
        print("log-in pressed")
        if self.robot_checkbox.isChecked():
            self._mutex.lock()
            self.client.username = self.username_text.text()
            self._mutex.unlock()
            self._mutex.lock()
            self.client.password = self.password_text.text()
            self._mutex.unlock()
            time.sleep(2)
            if self.client.client_singed is True:
                MainWindow.close()
        else:
            self.robot_label.show()
import photos2


def show_window(window):
    app2 = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    window.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app2.exec_())


