# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sign_in_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
import time

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QMutex


def show_sign_window(window):
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    window.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())


class Ui_signUpWindow(object):
    def __init__(self, Client):
        self.client = Client

    def setupUi(self, signUpWindow):
        signUpWindow.setObjectName("signUpWindow")
        signUpWindow.resize(800, 600)
        signUpWindow.setStyleSheet("background-color: rgb(0, 0, 0)")
        self.centralwidget = QtWidgets.QWidget(signUpWindow)
        self.centralwidget.setObjectName("centralwidget")
        self._mutex = QMutex()
        self.gamelogo = QtWidgets.QLabel(self.centralwidget)
        self.gamelogo.setGeometry(QtCore.QRect(40, 0, 721, 371))
        self.gamelogo.setObjectName("gamelogo")
        self.robot_box = QtWidgets.QCheckBox(self.centralwidget)
        self.robot_box.setGeometry(QtCore.QRect(640, 440, 151, 17))
        self.robot_box.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.robot_box.setObjectName("robot_box")
        self.username_taken = QtWidgets.QLabel(self.centralwidget)
        self.username_taken.setGeometry(QtCore.QRect(470, 380, 151, 21))
        self.username_taken.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.username_taken.setObjectName("username_taken")
        self.username_taken.hide()
        self.password_error = QtWidgets.QLabel(self.centralwidget)
        self.password_error.setGeometry(QtCore.QRect(470, 460, 161, 21))
        self.password_error.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.password_error.setObjectName("password_error")
        self.password_error.hide()
        self.pass_error_len = QtWidgets.QLabel(self.centralwidget)
        self.pass_error_len.setGeometry(QtCore.QRect(470, 490, 161, 21))
        self.pass_error_len.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.pass_error_len.setObjectName("pass_error_len")
        self.pass_error_len.hide()
        self.pass_error_num = QtWidgets.QLabel(self.centralwidget)
        self.pass_error_num.setGeometry(QtCore.QRect(470, 520, 161, 21))
        self.pass_error_num.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.pass_error_num.setObjectName("pass_error_num")
        self.pass_error_num.hide()
        self.signin_button = QtWidgets.QPushButton(self.centralwidget)
        self.signin_button.setGeometry(QtCore.QRect(640, 470, 151, 71))
        self.signin_button.setStyleSheet("background-color: rgb(0, 255, 255);\n"
                                         "font: 75 8pt \"Magneto\"; font-size: 35px;height: 20px;width: 45px;")
        self.signin_button.setObjectName("signin_button")
        self.firstname_text = QtWidgets.QLineEdit(self.centralwidget)
        self.firstname_text.setGeometry(QtCore.QRect(40, 410, 211, 41))
        self.firstname_text.setStyleSheet(";background-color: rgb(162, 47, 255);\n"
                                          "font: 75 8pt \"Magneto\"; font-size: 35px;height: 20px;width: 45px;")
        self.firstname_text.setText("")
        self.firstname_text.setObjectName("firstname_text")
        self.firstname_label = QtWidgets.QLabel(self.centralwidget)
        self.firstname_label.setGeometry(QtCore.QRect(40, 380, 211, 21))
        self.firstname_label.setStyleSheet(";background-color:rgb(255, 0, 0);\n"
                                           "font: 75 8pt \"Magneto\"; font-size: 20px;height: 10px;width: 30px;")
        self.firstname_label.setObjectName("firstname_label")
        self.lastname_text = QtWidgets.QLineEdit(self.centralwidget)
        self.lastname_text.setGeometry(QtCore.QRect(40, 500, 211, 41))
        self.lastname_text.setStyleSheet(";background-color: rgb(162, 47, 255);\n"
                                         "font: 75 8pt \"Magneto\"; font-size: 35px;height: 20px;width: 45px;")
        self.lastname_text.setObjectName("lastname_text")
        self.lastname_label = QtWidgets.QLabel(self.centralwidget)
        self.lastname_label.setGeometry(QtCore.QRect(40, 470, 211, 21))
        self.lastname_label.setStyleSheet(";background-color:rgb(255, 0, 0);\n"
                                          "font: 75 8pt \"Magneto\"; font-size: 20px;height: 10px;width: 30px;")
        self.lastname_label.setObjectName("lastname_label")
        self.username_text = QtWidgets.QLineEdit(self.centralwidget)
        self.username_text.setGeometry(QtCore.QRect(260, 410, 201, 41))
        self.username_text.setStyleSheet(";background-color: rgb(162, 47, 255);\n"
                                         "font: 75 8pt \"Magneto\"; font-size: 35px;height: 20px;width: 45px;")
        self.username_text.setObjectName("username_text")
        self.username_label = QtWidgets.QLabel(self.centralwidget)
        self.username_label.setGeometry(QtCore.QRect(260, 380, 201, 21))
        self.username_label.setStyleSheet(";background-color:rgb(255, 0, 0);\n"
                                          "font: 75 8pt \"Magneto\"; font-size: 20px;height: 10px;width: 30px;")
        self.username_label.setObjectName("username_label")
        self.robot_label = QtWidgets.QLabel(self.centralwidget)
        self.robot_label.setGeometry(QtCore.QRect(640, 420, 151, 16))
        self.robot_label.setStyleSheet(";background-color: rgb(253, 253, 253);")
        self.robot_label.setObjectName("robot_label")
        self.robot_label.hide()
        self.password_label = QtWidgets.QLabel(self.centralwidget)
        self.password_label.setGeometry(QtCore.QRect(260, 470, 201, 21))
        self.password_label.setStyleSheet(";background-color:rgb(255, 0, 0);\n"
                                          "font: 75 8pt \"Magneto\"; font-size: 20px;height: 10px;width: 30px;")
        self.password_label.setObjectName("password_label")
        self.password_text = QtWidgets.QLineEdit(self.centralwidget)
        self.password_text.setGeometry(QtCore.QRect(260, 500, 201, 41))
        self.password_text.setStyleSheet(";background-color: rgb(162, 47, 255);\n"
                                         "font: 75 8pt \"Magneto\"; font-size: 35px;height: 20px;width: 45px;")
        self.password_text.setObjectName("password_text")
        signUpWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(signUpWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        signUpWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(signUpWindow)
        self.statusbar.setObjectName("statusbar")
        signUpWindow.setStatusBar(self.statusbar)

        self.retranslateUi(signUpWindow)
        QtCore.QMetaObject.connectSlotsByName(signUpWindow)
        self.check_for_button_sign(signUpWindow)

    def retranslateUi(self, signUpWindow):
        _translate = QtCore.QCoreApplication.translate
        signUpWindow.setWindowTitle(_translate("signUpWindow", "MainWindow"))
        self.gamelogo.setText(
            _translate("signUpWindow", "<html><head/><body><p><img src=\":/photos2/logo3.png\"/></p></body></html>"))
        self.robot_box.setText(_translate("signUpWindow", "I am not a robot"))
        self.username_taken.setText(_translate("signUpWindow", "username taken"))
        self.password_error.setText(_translate("signUpWindow", "password not by rules"))
        self.pass_error_len.setText(_translate("signUpWindow", " password 8-16 letters long"))
        self.pass_error_num.setText(_translate("signUpWindow", " password must contain a number"))
        self.signin_button.setText(_translate("signUpWindow", "sign-in"))
        self.firstname_label.setText(_translate("signUpWindow", " firstname:"))
        self.lastname_label.setText(_translate("signUpWindow", " lastname:"))
        self.username_label.setText(_translate("signUpWindow", " username:"))
        self.password_label.setText(_translate("signUpWindow", " password:"))
        self.robot_label.setText(_translate("signUpWindow", " you might be a robot"))

    def check_for_button_sign(self, MainWindow):
        self.signin_button.clicked.connect(lambda: self.sign_up_pressed(MainWindow))

    def sign_up_pressed(self, MainWindow):
        if self.robot_box.isChecked():
            print("sign-in pressed")
            if len(self.password_text.text()) < 4 or len(self.password_text.text()) > 16:
                self.password_error.show()
                self.pass_error_len.show()
            elif has_numbers(self.password_text.text()) is False:
                self.password_error.show()
                self.pass_error_num.show()
            else:
                self._mutex.lock()
                self.client.username = self.username_text.text()
                self._mutex.unlock()
                self._mutex.lock()
                self.client.password = self.password_text.text()
                self._mutex.unlock()
                self._mutex.lock()
                self.client.first_name = self.firstname_text.text()
                self._mutex.unlock()
                self._mutex.lock()
                self.client.last_name = self.lastname_text.text()
                self._mutex.unlock()
            time.sleep(0.5)
            if self.client.client_singed is True:
                MainWindow.close()
        else:
            self.robot_label.show()

    import photos2


def has_numbers(inputString):
    return any(char.isdigit() for char in inputString)
