# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'w.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QMutex

MyText = " "


class Ui_TutorialWindow(object):
    def __init__(self, Client):
        self.client = Client

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self._mutex = QMutex()
        self.instructions_label = QtWidgets.QLabel(self.centralwidget)
        self.instructions_label.setGeometry(QtCore.QRect(10, 10, 741, 151))
        self.instructions_label.setStyleSheet("font-size: 25px;height: 10px;width: 35px;")
        self.instructions_label.setObjectName("instructions_label")
        self.germany_photo = QtWidgets.QLabel(self.centralwidget)
        self.germany_photo.setGeometry(QtCore.QRect(100, 200, 211, 181))
        self.germany_photo.setObjectName("germany_photo")
        self.germany_photo.hide()
        self.germany_label = QtWidgets.QLabel(self.centralwidget)
        self.germany_label.setGeometry(QtCore.QRect(330, 260, 121, 41))
        self.germany_label.setStyleSheet("font-size: 25px;height: 10px;width: 35px;")
        self.germany_label.setObjectName("germany_label")
        self.germany_label.hide()
        self.welldone_label = QtWidgets.QLabel(self.centralwidget)
        self.welldone_label.setGeometry(QtCore.QRect(450, 250, 131, 61))
        self.welldone_label.setStyleSheet("font-size: 25px;height: 10px;width: 35px;")
        self.welldone_label.setObjectName("welldone_label")
        self.welldone_label.hide()
        self.banana_photo = QtWidgets.QLabel(self.centralwidget)
        self.banana_photo.setGeometry(QtCore.QRect(70, 380, 251, 171))
        self.banana_photo.setObjectName("banana_photo")
        self.banana_photo.hide()
        self.banana_label = QtWidgets.QLabel(self.centralwidget)
        self.banana_label.setGeometry(QtCore.QRect(350, 450, 141, 51))
        self.banana_label.setStyleSheet("font-size: 25px;height: 10px;width: 35px;")
        self.banana_label.setObjectName("banana_label")
        self.banana_label.hide()
        self.excellent_label = QtWidgets.QLabel(self.centralwidget)
        self.excellent_label.setGeometry(QtCore.QRect(460, 450, 151, 51))
        self.excellent_label.setStyleSheet("font-size: 25px;height: 10px;width: 35px;")
        self.excellent_label.setObjectName("excellent_label")
        self.excellent_label.hide()
        self.continue_button = QtWidgets.QPushButton(self.centralwidget)
        self.continue_button.setGeometry(QtCore.QRect(550, 350, 211, 71))
        self.continue_button.setStyleSheet(";background-color: rgb(162, 47, 255);\n"
                                           "font: 75 8pt \"Magneto\"; font-size: 35px;height: 20px;width: 45px;")
        self.continue_button.setObjectName("continue_button")
        self.continue_button.hide()
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setGeometry(QtCore.QRect(20, 170, 181, 61))
        self.start_button.setStyleSheet(";background-color: rgb(162, 47, 255);\n"
                                        "font: 75 8pt \"Magneto\"; font-size: 35px;height: 20px;width: 45px;")
        self.start_button.setObjectName("start_button")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.check_for_button_log(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.instructions_label.setText(_translate("MainWindow", "this is a tutorial and a mic check,\n"
                                                                 "for the microphone to pick up your words \n"
                                                                 "you will need to be loud and clear.\n"
                                                                 "also you need to have a little pause between each phrase.\n"
                                                                 "now try saying these next words."))
        self.germany_photo.setText(
            _translate("MainWindow", "<html><head/><body><p><img src=\":/photos2/germany.png\"/></p></body></html>"))
        self.germany_label.setText(_translate("MainWindow", "Germany"))
        self.welldone_label.setText(_translate("MainWindow", "well done!"))
        self.banana_photo.setText(
            _translate("MainWindow", "<html><head/><body><p><img src=\":/photos2/banana.jpg\"/></p></body></html>"))
        self.banana_label.setText(_translate("MainWindow", "Banana"))
        self.excellent_label.setText(_translate("MainWindow", "excellent!!"))
        self.continue_button.setText(_translate("MainWindow", "continue"))
        self.start_button.setText(_translate("MainWindow", "start"))

    def check_for_button_log(self, MainWindow):
        self.start_button.clicked.connect(lambda: self.start_pressed(MainWindow))
        self.continue_button.clicked.connect(lambda: self.continue_pressed(MainWindow))

    def continue_pressed(self, MainWindow):
        print("continuepressed")
        self._mutex.lock()
        self.client.screen_state = 2
        self._mutex.unlock()
        MainWindow.close()

    def start_pressed(self, MainWindow):
        self.start_button.hide()
        self.germany_label.show()
        self.germany_photo.show()
        self.client.record = True


def show_tutorial_window(window):
    app2 = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    window.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app2.exec_())


import photos2
